// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/auth/reset-password": {
    params: {};
  };
  "/email-verification": {
    params: {};
  };
  "/calculator": {
    params: {};
  };
  "/store-guide": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/user-dashboard": {
    params: {};
  };
  "/admin-dashboard": {
    params: {};
  };
  "/edit-order/:orderId": {
    params: {
      "orderId": string;
    };
  };
  "/contact": {
    params: {};
  };
  "/terms-of-service": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/services" | "/auth" | "/forgot-password" | "/auth/reset-password" | "/email-verification" | "/calculator" | "/store-guide" | "/dashboard" | "/user-dashboard" | "/admin-dashboard" | "/edit-order/:orderId" | "/contact" | "/terms-of-service" | "/privacy-policy";
  };
  "routes/Home.tsx": {
    id: "routes/Home";
    page: "/";
  };
  "routes/Services.tsx": {
    id: "routes/Services";
    page: "/services";
  };
  "routes/Auth.tsx": {
    id: "routes/Auth";
    page: "/auth";
  };
  "routes/ForgotPassword.tsx": {
    id: "routes/ForgotPassword";
    page: "/forgot-password";
  };
  "routes/ResetPassword.tsx": {
    id: "routes/ResetPassword";
    page: "/auth/reset-password";
  };
  "routes/EmailVerification.tsx": {
    id: "routes/EmailVerification";
    page: "/email-verification";
  };
  "routes/Calculator.tsx": {
    id: "routes/Calculator";
    page: "/calculator";
  };
  "routes/StoreGuide.tsx": {
    id: "routes/StoreGuide";
    page: "/store-guide";
  };
  "routes/Dashboard.tsx": {
    id: "routes/Dashboard";
    page: "/dashboard";
  };
  "routes/UserDashboard.tsx": {
    id: "routes/UserDashboard";
    page: "/user-dashboard";
  };
  "routes/AdminDashboard.tsx": {
    id: "routes/AdminDashboard";
    page: "/admin-dashboard";
  };
  "routes/EditOrder.tsx": {
    id: "routes/EditOrder";
    page: "/edit-order/:orderId";
  };
  "routes/Contact.tsx": {
    id: "routes/Contact";
    page: "/contact";
  };
  "routes/TermsOfService.tsx": {
    id: "routes/TermsOfService";
    page: "/terms-of-service";
  };
  "routes/PrivacyPolicy.tsx": {
    id: "routes/PrivacyPolicy";
    page: "/privacy-policy";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/Home": typeof import("./app/routes/Home.tsx");
  "routes/Services": typeof import("./app/routes/Services.tsx");
  "routes/Auth": typeof import("./app/routes/Auth.tsx");
  "routes/ForgotPassword": typeof import("./app/routes/ForgotPassword.tsx");
  "routes/ResetPassword": typeof import("./app/routes/ResetPassword.tsx");
  "routes/EmailVerification": typeof import("./app/routes/EmailVerification.tsx");
  "routes/Calculator": typeof import("./app/routes/Calculator.tsx");
  "routes/StoreGuide": typeof import("./app/routes/StoreGuide.tsx");
  "routes/Dashboard": typeof import("./app/routes/Dashboard.tsx");
  "routes/UserDashboard": typeof import("./app/routes/UserDashboard.tsx");
  "routes/AdminDashboard": typeof import("./app/routes/AdminDashboard.tsx");
  "routes/EditOrder": typeof import("./app/routes/EditOrder.tsx");
  "routes/Contact": typeof import("./app/routes/Contact.tsx");
  "routes/TermsOfService": typeof import("./app/routes/TermsOfService.tsx");
  "routes/PrivacyPolicy": typeof import("./app/routes/PrivacyPolicy.tsx");
};