// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puhrnhslcyxnhgcfjsqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1aHJuaHNsY3l4bmhnY2Zqc3F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTQyOTAsImV4cCI6MjA2NTU3MDI5MH0.EGEqwBHTHAN47r-PVHzqd8q7jSzptPB549OPWXNmtZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);